In [2]:
import numpy as np

In [4]:
np.zeros((2, 4)) # np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.tri(3) # np.tri(n) 하삼각행렬

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [6]:
np.ones((2, 4)) # np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.full((2,5), 1.5) # np.full(shape, value)

array([[1.5, 1.5, 1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5, 1.5, 1.5]])

In [8]:
np.eye(5) # np.eye(n) 단위행렬

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.empty((2,3)) # np.empty(shape) 초기화되지 않은 배열 생성, 초기화가 없어서 배열 생성 비용이 저렴하고 빠름, 초기화되지않아서 기존 메모리 위치에 존재하는 값이 있으므로 무슨 수가 나올지 모름

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# _like() : 지정된 배열과 shape가 같은 행렬 생성
a1 = np.array([1,2,3,4,5])
print(a1)
print(np.zeros_like(a1))
print(np.ones_like(a1))
print(np.full_like(a1, 10))

[1 2 3 4 5]
[0 0 0 0 0]
[1 1 1 1 1]
[10 10 10 10 10]


In [17]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(1, 10, 5) # np.linspace(start, end, 간격) 균등한 간격으로 나눠줌

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
np.logspace(0, 1, 20) # np.logspace(start, end, 간격) 범위 내에서 균등한 간격으로 로그 스케일로 배열 생성

array([ 1.        ,  1.12883789,  1.27427499,  1.43844989,  1.62377674,
        1.83298071,  2.06913808,  2.33572147,  2.6366509 ,  2.97635144,
        3.35981829,  3.79269019,  4.2813324 ,  4.83293024,  5.45559478,
        6.15848211,  6.95192796,  7.8475997 ,  8.8586679 , 10.        ])

In [30]:
# random.random() : 랜덤한 수의 배열 생성
np.random.random((3,3))

array([[0.2938914 , 0.7942691 , 0.44504796],
       [0.3259822 , 0.56472449, 0.62329198],
       [0.47379155, 0.70286857, 0.00576802]])

In [32]:
np.random.randint(0, 10, (3,3)) # np.random.randint(start, end, shape) start부터 end-1사이의 수를 랜덤하게 뽑아 shape배열을 생성

array([[0, 8, 7],
       [9, 8, 4],
       [4, 9, 3]])

In [34]:
np.random.normal(0, 1, size=(2,4)) # np.random.normal(mu, std, size) normal distribution을 고려한 랜덤한 수를 뽑아 배열 생성

array([[-1.65271832,  0.84209452, -1.08763035,  0.22266139],
       [ 0.66866383,  1.83204632,  1.0453194 , -0.81194045]])

In [35]:
np.random.rand(3,3) # np.random.rand(row, col) uniform distribution을 고려한 랜덤한 수를 뽑아 배열 생성

array([[0.01283572, 0.29973732, 0.16063435],
       [0.13148863, 0.51354381, 0.43427048],
       [0.13847429, 0.586607  , 0.70779612]])

In [39]:
np.random.randn(2, 3) # np.random.randn(row, col) standard normal distribution을 고려한 랜덤한 수를 뽑아 배열 생성

array([[-0.75693614, -1.62524395, -0.37677798],
       [ 0.46936415,  1.00600368, -0.76179649]])

In [51]:
date = np.array('2023-03-26', dtype='datetime64[M]') # dtype= 'datetime[]'에 M을 넣으면 달까지 Y를 넣으면 연도만 D를 넣으면 일까지 계산됨
date

array('2023-03', dtype='datetime64[M]')

In [52]:
date + np.arange(12)

array(['2023-03', '2023-04', '2023-05', '2023-06', '2023-07', '2023-08',
       '2023-09', '2023-10', '2023-11', '2023-12', '2024-01', '2024-02'],
      dtype='datetime64[M]')

In [55]:
datetime = np.datetime64('2020-06-01 12:00:14.15', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:14.150000000')

In [58]:
a1 = np.array([1,2,3,4,5])
idx = np.array([[1, 2],
                [4, 3]])
print(a1[idx])

[[2 3]
 [5 4]]


In [66]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[1:, 1:])
print(a2[row, ::-1])
print(a2[:-1, col])

[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[3 2 1]
 [9 8 7]]
[[2 3]
 [5 6]]


In [71]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
print(a1)
c1 = np.insert(a1, 2, 10)
print(c1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[1 2 3 4 5]
[ 1  2 10  3  4  5]


In [73]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [148]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
arr = np.empty((0,2), int)
print(arr)
for i in range(3):
    arr = np.append(arr, np.array([[i, i]]), axis=0)
print(arr)
print(a2)
for i in range(3):
    a2[i, i] = 100
print(a2)
print(a2[[1, 2]])
print(a2[[1, 2], :])

[]
[[0 0]
 [1 1]
 [2 2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[100   2   3]
 [  4 100   6]
 [  7   8 100]]
[[  4 100   6]
 [  7   8 100]]
[[  4 100   6]
 [  7   8 100]]


In [150]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[1 2 3 4 5]
[1 3 4 5]
[1 2 3 4 5]


In [151]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


In [156]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:1, :1] = 50
print(a2_sub)
print(a2)

[[50  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[50  2]
 [ 4  5]]
[[50  2]
 [ 4  5]]
[[50  2]
 [ 4  5]]
[[50  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [158]:
a2 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(a2)
a2_sub = np.copy(a2)
print(a2_sub)
a2_sub[:1, :1] = 50
print(a2)
print(a2_sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[50  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [14]:
a2 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(a2)
print(a2.T)
print(a2.swapaxes(1,0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [15]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]])
print(a3)
print(a3.T)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [16]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# np.newaxis() : 새로운 축 추가
n1 = np.arange(1,10)
print(n1)
print(n1[np.newaxis, :5]) # 왼쪽에 생성하면 row로
print(n1[:5, np.newaxis]) # 오른쪽에 생성하면 column으로 축을 생성

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [22]:
n2 = np.random.randint(0, 10, (2,5))
print(n2)
n2.resize((5,2))
print(n2)
n2.resize((5,5)) # resize시 크기를 늘리면 늘어난 부분에 0을 채움
print(n2)
n2.resize(3,3) # resize시 크기를 줄이면 넘어가는 부분은 삭제하고 남은 부분으로 배열을 생성함
print(n2)

[[6 8 9 1 7]
 [0 4 7 4 6]]
[[6 8]
 [9 1]
 [7 0]
 [4 7]
 [4 6]]
[[6 8 9 1 7]
 [0 4 7 4 6]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[6 8 9]
 [1 7 0]
 [4 7 4]]


In [39]:
# append 
a2 = np.arange(1, 10).reshape(3,3)
b2 = np.arange(11, 20).reshape(3,3)
print(a2)
print(b2)
# a2 = np.append(a2, np.array([[10,10,10]]), axis=0)
# print(a2)
# a2 = np.append(a2, np.array([[10,10,10]]) axis=0)
# print(a2)
a2 = np.append(a2, b2, axis=1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [41]:
# concatenate : tuple이나 배열의 리스트를 인수로 사용해 배열 연결
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [42]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [43]:
a2 = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
a2 = np.array([[1,2,3],
                [4,5,6]])
np.concatenate([a2,a2], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [45]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [46]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [47]:
np.dstack([a2,a2]) # 깊이 스택, 3차원으로 연결

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [48]:
np.stack([a2,a2]) # 새로운 차원으로 연결

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [49]:
a1 = np.arange(0,19)
b1, c1 = np.split(a1, [10])
print(b1, c1)

[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18]


In [51]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2, c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]] [[7 8 9]]


In [52]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2, c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]]


In [55]:
# dsplit : 깊이 분할, 3차원으로 분할
a2 = np.arange(1, 28).reshape(3,3,3)
print(a2)
b2, c2 = np.dsplit(a2, [2])
print(b2, c2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]] [[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


In [57]:
a1 = np.array([1,2,3])
print(a1)
print(a1 + 5)

a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a2 + a1)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [62]:
print(np.exp(np.array(2))) # e ^ 2
print(np.exp2(np.array(5))) # 2 ^ 5

7.38905609893065
32.0


In [8]:
# prod() : 곱 계산
a2 = np.array([[1,2,3],
                [4,5,6]])
print(a2)
print(np.prod(a2)) # matrix의 모든 인자의 곱
print(np.prod(a2, axis = 0)) # 각 columns의 곱
print(np.prod(a2, axis = 1)) # 각 row의 곱

[[1 2 3]
 [4 5 6]]
720
[ 4 10 18]
[  6 120]


In [7]:
# cumpord() : 누적곱 계산
a2 = np.array([[1,2,3],
                [4,5,6]])
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis = 0))
print(np.cumprod(a2, axis = 1))

[[1 2 3]
 [4 5 6]]
[  1   2   6  24 120 720]
[[ 1  2  3]
 [ 4 10 18]]
[[  1   2   6]
 [  4  20 120]]


In [16]:
# dot()/matmul() : 접곱/행렬곱 계산
a2 = np.array([[1,2,3],
                [4,5,6]])
b2 = np.ones_like(a2).reshape(3,2)
print(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[1 2 3]
 [4 5 6]]
[[1 1]
 [1 1]
 [1 1]]
[[ 6  6]
 [15 15]]
[[ 6  6]
 [15 15]]


In [20]:
# tensordot() : 텐서곱 연산
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes=0))
print(np.tensordot(a2, b2, axes=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
45
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]


In [17]:
# np.cross() : 벡터 곱
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]


In [22]:
# inner() / outer() : 내적 / 외적
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]
[[1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9]]


In [24]:
a3, b3 = [1,2,3], [4,5,6]
print(np.inner(a3, b3))
print(np.outer(a3, b3))

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


##### np.mean : 평균
##### np.max : 최대값
##### np.argmax : 최대값의 index
##### np.min : 최소값
##### np.argmin : 최소값의 index
##### np.median : 중앙값

In [25]:
# percentile() : 백분위 수
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 25, 50, 75, 100], interpolation='linear'))
print(np.percentile(a1, [0, 25, 50, 75, 100], interpolation='higher'))
print(np.percentile(a1, [0, 25, 50, 75, 100], interpolation='lower'))
print(np.percentile(a1, [0, 25, 50, 75, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 25, 50, 75, 100], interpolation='midpoint'))

[0 1 2 3]
[0.   0.75 1.5  2.25 3.  ]
[0 1 2 3 3]
[0 0 1 2 3]
[0 1 2 2 3]
[0.  0.5 1.5 2.5 3. ]


In [27]:
# any()
a2 = np.array([[False]*3,
                [True]*3,
                [False]*3])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [ True  True  True]
 [False False False]]
True
[ True  True  True]
[False  True False]


In [28]:
# all()
a2 = np.array([[False]*3,
                [True]*3,
                [False]*3])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False False]
 [ True  True  True]
 [False False False]]
False
[False False False]
[False  True False]


In [38]:
# 비교연산은 boolean값으로 나온다
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)
print(a1 > 5)

print('-------------------------------------------------------')

a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 > 5))
print(np.count_nonzero(a2 > 5, axis=0))
print(np.count_nonzero(a2 > 5, axis=1))

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[False False False False False  True  True  True  True]
-------------------------------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
[1 1 2]
[0 1 3]


In [43]:
# np.close() : 배열 두개가 (z*le+02)% 내외로 가까우면 True, 아니면 False
# np.isinf() : 배열이 inf이면 True, 아니면 False
# np.isfinite() : 배열이 inf, nan이면 False, 아니면 True
# np.isnan() : 배열이 nan이면 True, 아니면 False
a1 = np.array([1,2,3,4,5])
b1 = np.array([1,3,3,4,5])
print(np.isclose(a1, b1))

print('-------------------------------------------------------')

a1 = np.array([np.nan, 1, np.NINF, 5, np.inf])
print(a1)
print(np.isnan(a1))
print(np.isinf(a1))
print(np.isfinite(a1))

[ True False  True  True  True]
-------------------------------------------------------
[ nan   1. -inf   5.  inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


In [49]:
a1 = np.arange(1, 10).reshape(3,3)
print(a1)
print((a1>5) & (a1 < 8))
print(a1[(a1>5) & (a1 < 8)])

print((a1<5) | (a1 > 8))
print(a1[(a1<5) | (a1 > 8)])

print((a1>5) ^ (a1 < 8))
print(a1[(a1>5) ^ (a1 < 8)])

print(~(a1>5))
print(a1[~(a1>5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True False False]
 [False False  True]]
[1 2 3 4 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


In [51]:
a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1)) # sort되었을때의 index값 return
print(a1)
a1.sort()
print(a1)

[3 7 7 9 5 3 9 1 6 6]
[1 3 3 5 6 6 7 7 9 9]
[3 7 7 9 5 3 9 1 6 6]
[7 0 5 4 8 9 1 2 3 6]
[3 7 7 9 5 3 9 1 6 6]
[1 3 3 5 6 6 7 7 9 9]


In [52]:
a1 = np.random.randint(1, 10, size = (3,3))
print(a1)
print(np.sort(a1, axis=0))
print(np.sort(a1, axis=1))

[[2 6 6]
 [6 8 5]
 [3 4 2]]
[[2 4 2]
 [3 6 5]
 [6 8 6]]
[[2 6 6]
 [5 6 8]
 [2 3 4]]


In [55]:
# partition() : 배열에서 k개의 작은 값을 반환
a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.partition(a1, 3))

print('-------------------------------------------------------')

a2 = np.random.randint(1, 30, size = (4,4))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[9 2 3 7 2 8 4 1 7 5]
[1 2 2 3 4 5 8 7 7 9]
-------------------------------------------------------
[[19  7 13 25]
 [18  4 17 16]
 [12 10 11  6]
 [20 22 28 11]]
[[13  7 19 25]
 [ 4 16 17 18]
 [ 6 10 11 12]
 [11 20 22 28]]
[[12  4 11  6]
 [18  7 13 11]
 [19 10 17 16]
 [20 22 28 25]]
[[13  7 19 25]
 [ 4 16 17 18]
 [ 6 10 11 12]
 [11 20 22 28]]


##### np.save() : numpy 배열 객체 1개를 파일에 저장 / 파일 종류 : 바이너리
##### np.savez() : numpy 배열 객체 여러개를 파일에 저장 / 파일 종류 : 바이너리
##### np.load() : numpy 배열 저장 파일로부터 객체 로딩 / 파일 종류 : 바이너리
##### np.loadtxt() : 텍스트 파일로부터 배열 로딩 / 파일 종류 : 텍스트
##### np.savetxt() : 텍스트 파일에 numpy 배열 객체 저장 / 파일 종류 : 텍스트

In [56]:
a = np.random.randint(1, 20, size = (4,4))
print(a)
np.save('a', a)

[[ 5  9  5  5]
 [14  8  8  2]
 [12  8 12 15]
 [10 12  9 14]]


In [66]:
npy = np.load('a.npy')
print(npy)

[[ 5  9  5  5]
 [14  8  8  2]
 [12  8 12 15]
 [10 12  9 14]]


In [65]:
b = np.random.randint(1, 20, size = (4,4))
print(b)
np.savez('ab', a, b)

[[11  4 13 19]
 [ 8 15  5 11]
 [11 15 15 16]
 [15 11 10  3]]


In [68]:
npz = np.load('ab.npz')
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[ 5  9  5  5]
 [14  8  8  2]
 [12  8 12 15]
 [10 12  9 14]]
[[11  4 13 19]
 [ 8 15  5 11]
 [11 15 15 16]
 [15 11 10  3]]


In [70]:
print(a)
np.savetxt('a.csv', a, delimiter=',')

[[ 5  9  5  5]
 [14  8  8  2]
 [12  8 12 15]
 [10 12  9 14]]


In [75]:
cs = np.loadtxt('a.csv', delimiter=',')
print(cs)

[[ 5.  9.  5.  5.]
 [14.  8.  8.  2.]
 [12.  8. 12. 15.]
 [10. 12.  9. 14.]]
